import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Providers from './providers'


const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>



        <Header />
        {/* NAVBAR */}

        {/* SEARCHBOX */}
        <div className=' max-w-6xl mx-auto my-4'>
          {children}
        </div>

        {/* FOOTER */}

      </Providers>
      </body>
    </html>
  )
}
